### ISSUE TITLE
Confirmer auprès de la Ville si accepté d'inclure fiches de boîtes, de bureaux, d'entrepreneurs, d'artisans, etc.

### ISSUE THREAD

**Issue by emmnull** [CUPUM/nplex#10]
Vérifier si la ville est ouverte à l'idée que la plateforme expose (sans nécessairement en faire la _promotion_) des acteurs privés des projets tels que des: 

- Entrepreneurs
- Boîtes de design ou d'architecture
- Bureaux d'arrondissement, de la Ville
- Organismes
- Artisans
- etc.

## À faire:

- [x] Trouver avec qui entrer en contact pour valider ce point
- [x] Rédiger et envoyer courriel

**Comment by iolyd** [comment]
Validé lors d'une rencontre de suivi.
