### ISSUE TITLE
Task: remettre nplex en ligne

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex#132]
# Task Description
L'URL indique que le site n'est pas en ligne

![image](https://user-images.githubusercontent.com/8132989/214345827-3e9ce31b-3994-4ff4-ae31-5ba43bf9f92a.jpeg)

# List of actions
- [ ] Action: 
- [ ] Action:

**Comment by iolyd** [comment]
Related to #130

**Comment by iolyd** [comment]
Le site est maintenant à nouveau en ligne et utilisera dorénavant Vercel pour les déploiements (même service que celui utilisé pour l'aggrégateur). Je regarderai avec @hugobb prochainement pour voir comment nous pourrons y coordonner une équipe commune. Il faudra aussi déterminer comment les abonnements payants seront gérés pour correctement attributer la/les factures au fonds des projets respectifs.
