### ISSUE TITLE
Task: Apprendre les bases de SvelteKit

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#164]
# Task Description

Vu l'avancement sur la familiarisation avec les APIs d'intérêt, @frroye je te propose de commencer à explorer [SvelteKit](https://kit.svelte.dev/), le framework utilisé pour l'interface de Nplex.

Les deux meilleures avenues pour débuter, selon moi, sont de suivre le tutoriel interactif, puis de créer un projet test sur ton ordinateur. Nplex (et l'aggrétgateur) est développé avec TypeScript, une variante syntaxique de JavaScript qui permet d'utiliser du _static typing_. Comme une bonne partie du chantier que j'envisage implique le typage des données, je te propose de créer le projet test en TypeScript tout en adoptant ses features progressivement (nous porrons faire une petite séance pour regarder ensemble ce que ça implique).

En parallèle, nous pourrons aussi définir l'approche souhaitable pour gérer les requêtes de données, à savoir:
- fonctionner avec des endpoints / loads de SvelteKit, ou
- fonctionner avec des requêtes directes (_fetch_) côté-client

Il y aura certaines contraintes à prendre en compte, notamment au niveau de l'hébergement, qui risquent de faire pencher la balance vers des requêtes côté-client, sans passer par le serveur de l'application. Mais dans tous les cas, je crois que ça reste pertinent pour toi d'explorer un peu la philosophie que SvelteKit met de l'avant pour le chargement des données à partir du serveur (https://kit.svelte.dev/docs/load)

# List of actions
- [ ] Compléter le tutoriel interactif: https://learn.svelte.dev/tutorial/welcome-to-svelte
- [ ] Lire la documentation au besoin: https://kit.svelte.dev/docs/introduction
  - Se familiariser avec le _state management_, i.e. surtout lire sur les _stores_
  - Se familiariser avec l'utilisation des 2 environnements applicatifs: le côté serveur et le côté client
  - Débuter avec des simples `fetch`

**Comment by frroye** [comment]
Salut @iolyd !
Je t'ai ajouté au repo https://github.com/CUPUM/test-nplex-mtl-api, dans lequel j'ai essayé de faire comme on s'était dit (2 boutons, un qui appelle l'API directement et l'autre qui passe par le "serveur" sveltekit"). Est-ce que tu vas être là demain pm? Si tu as du temps j'aurais quelques questions!

**Comment by iolyd** [comment]
Super! Oui je serai là demain, par contre en pm ça risque d'être serré. Pourrais-tu en am?

**Comment by frroye** [comment]
J'ai un cours ce matin qui fini à 11h30, donc je pourrais à midi? Sinon demain n'importe quand!
