### ISSUE TITLE
Epic: Mise en ligne de 100 projets sur Nplex pour le 1er octobre

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex#175]
# Epic description:
Recruter une vingtaine de bureaux d’architecture pour mettre en ligne environ 100 petits projets exemplaires situés dans la ville de Montreal. 

Les bureaux devraient être identifiés, contactés, relancé (avec parcimonie), accompagnés et remercier.

Chaque bureau devrait remplir au moins 5 fiches projets, en particulier les sections « Général », « Lieu », et « Galerie ».

Il faut bien construire un argumentaire convainquant pour que les bureaux aient envie d’utiliser la plateforme : projet accompagné par la ville de Montréal, visibilité auprès de citoyens et des arrondissements, à but non lucratif, aucune cessation des droits 

# List of tasks 

- [x] #181
- [x] #182
- [x] #183

**Comment by frroye** [comment]
Liens utiles

[contact des bureaux partenaires](https://github.com/CUPUM/nplex-organisation/issues/2#issue-1566180740)
[ancien courriel de recrutement](https://github.com/CUPUM/nplex-organisation/blob/5db8a9c04194d4082d621ae7d6c38e2726397371/partenariats/nplex-modele_demande-partenariat.docx)

**Comment by frroye** [comment]
@roxanekasprzyk extrait de nplex pour les profils utilisateurs 👍 

> Afin de répondre à la pression exercée par le secteur de la construction sur ses ressources internes, tout en maintenant sa mission de promouvoir des pratiques de constructions durables et en harmonie avec le contexte architectural et urbanistique de la ville, la CUPUM doit formuler un projet répondant aux besoins de cinq publics cibles prioritaires :
>
>les citoyens demandeurs de permis de construction
>les citoyens impliqués dans des processus participatifs
>les citoyens membres de comités consultatifs d’urbanisme (CCU)
>les élus municipaux
>les professionnels de l’aménagement qui encadre des processus consultatifs d’aménagement
