### ISSUE TITLE
Task: Faire valider l’utilisation du logo de ville sur le matériel nplex pour le 1er octobre

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex#177]
# Task description
Selon la convention de contribution signée avec la ville de Montréal, nous devons faire valider les mentions de cette contribution et le logo de la ville de Montréal sur tous les documents de communication du projet (posts réseaux sociaux, cartons d’invitation, posters, etc.) ainsi que sur le site de nplex lui-même. @iolyd peut donner accès aux conditions e visibilité

# List of tasks:
- [ ] Task: Planifier la validation de l’utilisation du logo de la ville (issues et milestones)

**Comment by SarahTannir** [comment]
Hello @sjinko! I can't seem to find the logo of Ville de Montréal on github. Do you have it by any chance?

**Comment by SarahTannir** [comment]
Hello @sjinko! I can't seem to find the logo of Ville de Montréal on github. Do you have it by any chance?

**Comment by sjinko** [comment]
I don’t have it, but I think there is a link in the Convention to a “trousse d’identité visuelle”. Or you can email Jacinthe.
