### ISSUE TITLE
Action: Faire la liste des contacts sous un document Excel (pour le 5 septembre)

### ISSUE THREAD

**Issue by frroye** [CUPUM/nplex#185]
# Task description:
Faire la liste des contacts sous un [document Excel](https://docs.google.com/spreadsheets/d/13CyOMup9AjmSZ2k-uvlfg9h9nl4-MnykT3FnYKM6iSY/edit?usp=sharing)

# List of tasks 
- [x] Action: Mettre les firmes déjà partenaire dans le excel
- [x] Action: Noter d'autres firmes potentielles

**Comment by frroye** [comment]
[contact des bureaux partenaires](https://github.com/CUPUM/nplex-organisation/issues/2#issue-1566180740)

**Comment by roxanekasprzyk** [comment]
Oui c'est possible que sur leur site internet ce ne soit pas leurs références principales (dans les projets réalisés), en revanche ils le mentionnent toujours quelque part (dans la présentation de l'agence par exemple).

**Comment by frroye** [comment]
Ok j'ai mis une 30aine de firmes dans le doc en cherchant "architecte" sur Google map. Vous pourrez regarder et peut-être indiquer dans la colonne note s'il y en a des "pas cool"?

**Comment by SarahTannir** [comment]
Ok je vais réviser et rank ces 50 firmes suivant:
1. Follows all criteria (à mtl, targeted profile, already accepted etc.)
2. Follows moderately all the criteria
3. Firm outside of mtl but has projects in mtl

**Comment by roxanekasprzyk** [comment]
Merci beaucoup @frroye @SarahTannir 
Je vais checker la liste des firmes inscrites à l'ordre des architectes

**Comment by roxanekasprzyk** [comment]
Voici le lien de la liste des firmes que j'ai rajouté dans le document Excel : https://designmontreal.com/repertoire-designers

**Comment by roxanekasprzyk** [comment]
Hello ! 
Vous trouverez le partage des firmes sur le fichier Excel. Vous pouvez mettre votre prénom en face de la couleur que vous choisissez. 
Bonne journée !
