### ISSUE TITLE
Action: Rédiger le courriel de présentation (pour le 1 septembre)

### ISSUE THREAD

**Issue by frroye** [CUPUM/nplex#186]
# Task description:
Rédiger le courriel de présentation/ prise de contact avec les firmes

# List of tasks 
- [x] Action: Rédiger une première version du courriel

**Comment by frroye** [comment]
[ancien courriel de recrutement](https://github.com/CUPUM/nplex-organisation/blob/5db8a9c04194d4082d621ae7d6c38e2726397371/partenariats/nplex-modele_demande-partenariat.docx)

**Comment by roxanekasprzyk** [comment]
Bonjour @iolyd 

Peut-on utiliser la lettre déjà écrite [modèle demande partenariat](https://github.com/CUPUM/nplex-organisation/blob/5db8a9c04194d4082d621ae7d6c38e2726397371/partenariats/nplex-modele_demande-partenariat.docx)
A t-elle été rédigée justement pour le recrutement des firmes ? 

Eventuellement si tu es ok, on peut y rajouter des exemples de Screenshot de la plateforme pour leur donner un exemple visuel. 
Penses tu qu'il est pertinent de la traduire également en anglais ? 

Merci à toi, 
Roxane

**Comment by iolyd** [comment]
@roxanekasprzyk , le modèle de lettre est bon à l'exception de quelques éléments:

- Je crois qu'il faudrait modifier la partie où nous disions que nous ferions nous même l'entrée de donnée pour plutôt mettre l'emphase sur le fait que nous invitons les bureaux à être des éditeurs de contenu
- Dans le premier paragraphe, je me demande si "...pour valoriser l’adoption de bonnes pratiques en design." ne serait pas plutôt "... pour valoriser auprès des citoyen.ne.s l'expertise locale en design et favoriser l'adoption de bonnes pratiques tant par les particuliers que par les institutions et les professionnels de l'industrie."

Pour la question des captures d'écran, j'attendrais encore quelques jours pour voir où j'en arrive dans le développement de l'interface. Mais oui, si j'avance assez d'ici la semaine prochaine je vous partagerai des captures (et une invitation pour vous inscrire sur la plateforme)

Je crois qu'une traduction en anglais serait pertinente vu que la plateforme est désormais bilingue, mais ce n'est pas essentiel/prioritaire.

Laisse-moi savoir si ça ne répond pas à tes questions.

**Comment by roxanekasprzyk** [comment]
Merci, ça répond à mes questions, je vais prendre en considération tes conseils pour les intégrer dans la lettre. 
Ok merci beaucoup pour les captures d'écran, on verra la semaine prochaine suivant l'avancée.

**Comment by roxanekasprzyk** [comment]
@iolyd , Je te propose cette [lettre](https://github.com/CUPUM/nplex-organisation/blob/main/partenariats/kasprzyk-nplex-modele_demande-partenariat-20230830.docx) que j'ai modifié suivant tes derniers conseils. 
Laisse moi savoir si tu penses qu'il y a d'autres modifications, 
Merci à toi

**Comment by iolyd** [comment]
@roxanekasprzyk C'est bien! Je te propose quelques modifs très mineures ici: https://github.com/CUPUM/nplex-organisation/blob/main/partenariats/beaudrymarchand-nplex-modele_demande-partenariat-20230830.docx, autrement c'est bon pour envoi selon moi.

**Comment by frroye** [comment]
Est-ce que on devrait préciser dans le courriel que ça doit être des projets à Montréal? Ex: "La plateforme a pour objectif de promouvoir une diversité de projets d’aménagement *à Montréal* qui sauront susciter l’intérêt tant des intervenants ..."? Ou ce n'est pas nécessaire?

**Comment by frroye** [comment]
@roxanekasprzyk répondse de Emmanuel en live: oui c'est mieux de préciser à Montréal, sur le territoire de Montréal. On s'en parle demain de toute façon! :)

**Comment by roxanekasprzyk** [comment]
Merci pour vos corrections ! 
Voici [la lettre finale](https://github.com/CUPUM/nplex-organisation/blob/main/partenariats/kasprzyk-nplex-modele_demande-partenariat-20230830.docx)
