### ISSUE TITLE
Action: Traduire le courriel en anglais (pour le 1 septembre)

### ISSUE THREAD

**Issue by roxanekasprzyk** [CUPUM/nplex#187]
Suggestions: add logo for credibility, write an official letter signed by Emmanuel and Shin instead of a long email, make the email more personal (ex: I'm a research assistant at the UNESCO Chair etc.)

**Comment by SarahTannir** [comment]
Allô @roxanekasprzyk, je n'arrive pas à trouver le courriel! Tu l'a déposer ou? :)

**Comment by roxanekasprzyk** [comment]
Hola, il est [ici](https://github.com/CUPUM/nplex-organisation/blob/main/partenariats/kasprzyk-nplex-modele_demande-partenariat-20230830.docx)
