### ISSUE TITLE
Task: Faire valider le courriel par Shin

### ISSUE THREAD

**Issue by SarahTannir** [CUPUM/nplex#188]
- [x] Action: Validate[ letter](https://github.com/CUPUM/nplex-organisation/blob/main/partenariats/lettre-partenariat_entreprises-20230906.docx) to be sent to firms
- [x] Action: Sign letter 
- [x] Action: Validate [email](https://github.com/CUPUM/nplex-organisation/blob/4406948068a50dcace2aaf7d41881ad4a990c3a0/partenariats/roy_tannir-courriel-premier_contact_partenariat-20230906.docx) with screenshots (refer to below)
- [x] Action: Send Sarah the logo of Ville de Montreal (to be inserted in the letter)

**Comment by SarahTannir** [comment]
![image_nplex-01](https://github.com/CUPUM/nplex/assets/99455471/06ab6bdd-961f-45e1-93d8-5754d60198ce)
![image_nplex-02](https://github.com/CUPUM/nplex/assets/99455471/616e5e70-b8f3-4d94-8e7b-f4128bb489d9)
![image_nplex-03](https://github.com/CUPUM/nplex/assets/99455471/daec9570-7d1d-45a0-90e5-94c4f4f357e2)

**Comment by sjinko** [comment]
J’ai modifié le contenu légèrement et remplacé le template de la lettre (ancien me semble-t-il). 
Pour l’envoie, je suggère que tous les courriels soient envoyés par une seule personne: @roxanekasprzyk de manière à centraliser les réponses et garder un log des bureaux intéressés.
