### ISSUE TITLE
Task: Définir le programme du 5 à 7

### ISSUE THREAD

**Issue by roxanekasprzyk** [CUPUM/nplex#194]
# Task: Définir le programme du 5 à 7
Définir un programme de la soirée. Planifier les interventions. 

[Programme détaillé](https://udemontreal-my.sharepoint.com/:x:/g/personal/sarah_tannir_umontreal_ca/EQDQg91kVvNFh_9WxBQwLecB8ZkMtLvD-NawvOy9mIiq8w?e=4%3ALJUByl&fromShare=true&at=9)

- 16h15 à 17h00: Préparation de la salle, réception des bouchées et de l'alcool
- 17h00 à 17h30: Arrivée des invités
- 17h30 à 17h45: Mot d'accueil de Shin (5 min), présentation de Nplex (7 min), interventions/mot de la ville ou autre partenaire (2-3 min), mot de la fin de Shin
- 17h45 à 19h00 : Réseautage
- 19h00 à ... : Rangement de la salle

# List of tasks 

- [ ] Action: Valider le programme de la soirée ci-dessus (Shin)
- [x] #212
- [x] #213
- [x] #214

**Comment by frroye** [comment]
Concernant l'utilisation du projecteur dans le hall d'entrée, il est branché en permanence à un ordi qui se trouve dans une petite salle dans la salle 1120 (amphithéatre qui donne sur le hall d'entrée). Le technicien m'a dit que ce n'est pas trop possible d'utiliser notre propre ordi par exemple pour projeter en tant réel l'utilisation de Nplex, puisque la configuration est complexe, vieille et il faudrait des adaptateurs aditionnels. 

**Ce qui est possible c'est de projeter une présentation power point + changer les diapos avec une manette : est-ce que ça convient pour la présentation?**
