### ISSUE TITLE
Task: Envoyer le formulaire aux firmes

### ISSUE THREAD

**Issue by roxanekasprzyk** [CUPUM/nplex#197]
# Task description:
Envoyer le formulaire pour les projets aux firmes

**Comment by roxanekasprzyk** [comment]
Salut @sjinko @iolyd 
j'ai une question pour vous, je reçois des réponses des firmes d'architecture qui me disent que la plupart de leurs projets résidentiels dépassent le budget maximum d'1.25 millions de dollars. Est-ce que nous acceptons tout de même ces projets ou ce n'est pas ce que vise la plateforme ? 
merci à vous

**Comment by iolyd** [comment]
Pour info, j'ai échangé mon opinion avec @roxanekasprzyk par courriel:
> Je suis hésitant à intégrer de tels projets. En dépassant 1.25M ça représente des coûts qui commencent à s’éloigner un peu de la visée initiale de Nplex.
>
> ...Pour l’instant, nous pourrions quand même demander aux firmes qui le veulent de compléter leurs fiches en leur précisant que nous allons réviser nos contraintes à l’interne.

**Comment by sjinko** [comment]
Je suis plutot d’avis qu’on les accepte, et qu’une fois le matériel en main, on décide si on les intègre ou non à la plateforme.

Je conçois bien que 1,25 M peut sembler beaucoup, mais des projets à 500 000$ se font maintenant pour 1M$.



From: Emmanuel Beaudry Marchand ***@***.***>
Date: Monday, October 2, 2023 at 13:53
To: CUPUM/nplex ***@***.***>
Cc: Shin Koseki ***@***.***>, Mention ***@***.***>
Subject: Re: [CUPUM/nplex] Task: Envoyer le formulaire aux firmes (Issue #197)

Pour info, j'ai échangé mon opinion avec @roxanekasprzyk<https://github.com/roxanekasprzyk> par courriel:

Je suis hésitant à intégrer de tels projets. En dépassant 1.25M ça représente des coûts qui commencent à s’éloigner un peu de la visée initiale de Nplex.

...Pour l’instant, nous pourrions quand même demander aux firmes qui le veulent de compléter leurs fiches en leur précisant que nous allons réviser nos contraintes à l’interne.
