### ISSUE TITLE
Obtenir des milestones du CENR

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex#2]
tel que discuté le 7 octobre

**Comment by sjinko** [comment]
Bonjour @kamgangc, pourriez-vous nous fournir tous les milestones du développement backend (avec dates) sur lesquelles nous allons contribuer?

**Comment by Mamyrusses** [comment]
Vous voulez que je les mettent directement dans Git j'imagine ?

**Comment by sjinko** [comment]
Ça serait bien oui

**Comment by sjinko** [comment]
@iolyd on a intégré ces milestone dans nos projets GH?

**Comment by iolyd** [comment]
@sjinko En fait les milestones établis par le CEN-R dans le repo [nplex-backend](https://github.com/CUPUM/nplex-backend/issues) (que je fermerai bientôt) ne sont plus valides: ils concernent principalement l'élaboration des définitions _swaggers_ de l'API, cependant ce travail est maintenant complété automatiquement par le service _Supabase_ en fonction des tableaux que l'on ajoute à la base de données.

Je dirais que le seul milestone restant en lien avec le CEN-R est la livraison des fichiers de la carte conceptuelle (confirmation de la version finale accessible sur [_Miro_](https://mandrillapp.com/track/click/30166792/miro.com?p=eyJzIjoiemlTVlllWkxTaEtJczBaUzJuRXZzTElKVkt3IiwidiI6MSwicCI6IntcInVcIjozMDE2Njc5MixcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL21pcm8uY29tXFxcL2FwcFxcXC9ib2FyZFxcXC9vOUpfbG1oV0FSYz0_dXRtX3NvdXJjZT1ub3RpZmljYXRpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249ZGFpbHktdXBkYXRlcyZ1dG1fY29udGVudD1nby10by1ib2FyZFwiLFwiaWRcIjpcImE2ZGMzNDVmYzJlMDQ4NDVhOWNkYjUxMDc2NzU1MTc3XCIsXCJ1cmxfaWRzXCI6W1wiNTkwNDViNGU4NDMyOTYwMTM2OTM1MzIyYWRmY2ZlOWQzMTc2MjZiYVwiXX0ifQ)) et des _outlines_ des tableaux de données.

@Sernoult pourrais-tu confirmer que ce sont là bien les livrables escomptés?

**Comment by iolyd** [comment]
Je ferme ce issue considéré comme non-applicable à ce stade-ci, à rouvrir selon ce qui sera déterminé pour la suite de la collaboration avec le CEN-R.
