### ISSUE TITLE
Action: Inviter les personnes impliquées de la ville de Montréal, membres du comité conseil, bureaux partenaires 

### ISSUE THREAD

**Issue by roxanekasprzyk** [CUPUM/nplex#206]
# List of tasks 

- [x] Action: Envoyer une invitation au membres du comité conseil 
- [x] Action: Envoyer une invitation aux bureaux partenaires 
- [x] Action: Envoyer une invitation aux membres de la ville de Montréal 
- [ ] Action: Intégrer ces invités dans la liste des invités

**Comment by roxanekasprzyk** [comment]
Salut @iolyd 

Aurais tu la liste des membres du comité conseil et des bureaux partenaires pour que je puisse leur envoyer une invitation ?
Merci à toi,

**Comment by iolyd** [comment]
Voici les membres du comité conseil:
- Sébastien Aumais: sebastien.aumais@montreal.ca
- Catherine Gingras: catherine.gingras@montreal.ca
- Jeanne Leblanc: jeanne.leblanc-trudeau@montreal.ca
- Elise Lacoursière Bourget: elise.lacoursierebourget@montreal.ca
- Mathias Losco: mathias.losco@montreal.ca
- Julien Rozon: julien.rozon@montreal.ca
- Jean-François Lusignan: jeanfrancois.lusignan@montreal.ca

**Comment by iolyd** [comment]
Voici les membres des bureaux partenaires qui ont participé à nos activités:
- Marie-Eve Lamarre Brodsky: marie@s-uwa.ca
- Olivier Lajeunesse-Travers: olivier@microclimat.ca
- Josianne Ouellet-Daudelin: josianne@lmccomber.ca

**Comment by roxanekasprzyk** [comment]
merci beaucoup @iolyd est ce que je dois envoyer une invitation pour les membres de la ville ?

**Comment by iolyd** [comment]
@roxanekasprzyk Bonne question. J'aurais tendance à dire oui comme ce sont les collaborateurs les plus présents dans notre démarche participative

**Comment by roxanekasprzyk** [comment]
ok merci, as tu la liste des contacts ?

**Comment by iolyd** [comment]
Ah, tu parles d'autres membres que ceux-ci?

> Voici les membres du comité conseil:
> 
> * Sébastien Aumais: [sebastien.aumais@montreal.ca](mailto:sebastien.aumais@montreal.ca)
> * Catherine Gingras: [catherine.gingras@montreal.ca](mailto:catherine.gingras@montreal.ca)
> * Jeanne Leblanc: [jeanne.leblanc-trudeau@montreal.ca](mailto:jeanne.leblanc-trudeau@montreal.ca)
> * Elise Lacoursière Bourget: [elise.lacoursierebourget@montreal.ca](mailto:elise.lacoursierebourget@montreal.ca)
> * Mathias Losco: [mathias.losco@montreal.ca](mailto:mathias.losco@montreal.ca)
> * Julien Rozon: [julien.rozon@montreal.ca](mailto:julien.rozon@montreal.ca)
> * Jean-François Lusignan: [jeanfrancois.lusignan@montreal.ca](mailto:jeanfrancois.lusignan@montreal.ca)

Jacinthe De Guire: jacinthe.deguire@montreal.ca
Patrick Marmen: patrick.marmen@montreal.ca

Nous pouvons leur envoyer l'invitation pour être systématique dans nos envois, mais ils nous ont indiqué en rencontre qu'il ne seront pas disponible le 10.

**Comment by roxanekasprzyk** [comment]
@sjinko @iolyd Connaissez vous M.Tran ? Puis-je lui envoyer une invitation si vous avez son contact ? 
<img width="682" alt="image" src="https://github.com/CUPUM/nplex/assets/124221528/8d9edd54-d376-44aa-a5d4-748ef2205c09">

**Comment by iolyd** [comment]
Je ne connais pas M. Tran et ne sais pas comment il est lié à M. Rozon.

**Comment by sjinko** [comment]
Oui, vous pouvez inviter M. Cuong Tran

cuong16 at hotmail.com

________________________________
