### ISSUE TITLE
Action: Inviter les membres de la faculté de l'aménagement

### ISSUE THREAD

**Issue by roxanekasprzyk** [CUPUM/nplex#207]
# Task description: 
Inviter les membres de la faculté de l'aménagement

# List of tasks:
- [x] Action: Lister les membres de la faculté de l'aménagement à inviter
- [x] Action: Leur envoyer un courriel d'invitation à l'évènement (@roxanekasprzyk)

**Comment by sjinko** [comment]
Les personnes à inviter seraient 

[myriam.ackad@umontreal.ca](mailto:myriam.ackad@umontreal.ca)
[marie.torres-toulemont@umontreal.ca](mailto:marie.torres-toulemont@umontreal.ca) 
[josee.gascon@umontreal.ca](mailto:josee.gascon@umontreal.ca)
[isabelle.thomas@umontreal.ca](mailto:isabelle.thomas@umontreal.ca)
[carmela.cucuzzella@umontreal.ca](mailto:carmela.cucuzzella@umontreal.ca)
[genevieve.letourneau-guillon@umontreal.ca](mailto:genevieve.letourneau-guillon@umontreal.ca)
