### ISSUE TITLE
Task: Retrouver la liste des indicateurs d'exemplarité

### ISSUE THREAD

**Issue by frroye** [CUPUM/nplex#208]
# Task description
Retrouver la liste des indicateurs d'exemplarité dans les issues. Rassembler les liens des ressources/documents produits en lien avce les indicateurs d'exemplarité ici. 

# List of tasks:
- [x] Task: Retrouver les documents qui listent les indicateurs d'exemplarité

**Comment by frroye** [comment]
[CRITÈRES D’EXEMPLARITÉ DES PROJET – Document de travail](https://udemontreal-my.sharepoint.com/:w:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/Eb10mBdOv6dGspMml_sum3oBHswO8ULatFHNykBHHKNhuA?e=szmm6b)

**Comment by frroye** [comment]
Salut @iolyd, juste valider avec toi, est-ce que le premier document ci-haut ([CRITÈRES D’EXEMPLARITÉ DES PROJET – Document de travail](https://udemontreal-my.sharepoint.com/:w:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/Eb10mBdOv6dGspMml_sum3oBHswO8ULatFHNykBHHKNhuA?e=szmm6b)) c'est pas mal là qu'on va trouver l'info pour les indicateurs d'exemplarité? Ou il y avait de l'info importante ailleurs?

**Comment by iolyd** [comment]
@frroye, oui c'est pas mal ce document qui contient tout le travail fait par les auxiliaires précédent au sujet des critères et des catégories de critères.
