### ISSUE TITLE
Action: Préparer une présentation power point de Nplex

### ISSUE THREAD

**Issue by frroye** [CUPUM/nplex#212]
# Task: Préparer une présentation visuelle de Nplex
Préparer une présentation visuelle/power point avec par exemple des captures d'écran de Nplex, qui va défiler en boucle durant l'évènement.

* Il ne sera pas possible de projeter à l'écran l'utilisation de nplex en tant réel. 
* Si tu veux m'envoyer des captures d'écran de la plateforme je peux m'occuper de juste les rassembler dans un power point avec défilement à chaque x secondes.

# List of tasks 

- [ ] Action: Préparer une présentation visuelle

**Comment by iolyd** [comment]
Salut @frroye, est-ce qu'il y a possibilité d'inclure des captures vidéo?

**Comment by frroye** [comment]
Oui! Je pourrai les convertir en gif et comme le vidéo jouera directement sur power point, sans avoir besoin de clicker
