### ISSUE TITLE
Task: Rédiger le contenu de la section Guides

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#255]
# Description:
Compléter la section Guides en se basant sur le [guide déjà rédigé](https://udemontreal-my.sharepoint.com/:w:/r/personal/emmanuel_beaudry_marchand_umontreal_ca/_layouts/15/Doc.aspx?sourcedoc=%7B179874BD-BF4E-46A7-B293-2697FB2E9B7A%7D&file=nplex-guide_exemplarit%25u00e9.docx&action=default&mobileredirect=true)

Le guide s’adresse principalement aux utilisateurs
Fichiers draft du guide se situent dans la branche Contenu : content/guide_fr.md et content/guide_en.md 

# List of actions

- [x] #267
- [x] #268
- [x] Action: Valider le contenu du fichier dans la branche contenu

**Comment by frroye** [comment]
@iolyd où est-ce que je peux avoir accès au guide que Agathe a rédiger? merci!

**Comment by iolyd** [comment]
@frroye Le document qui contient le guide est disponible sur OneDrive ici: https://udemontreal-my.sharepoint.com/:w:/r/personal/emmanuel_beaudry_marchand_umontreal_ca/Documents/CUPUM/Nplex/Conception/nplex-guide_exemplarit%C3%A9.docx?d=w179874bdbf4e46a7b2932697fb2e9b7a&csf=1&web=1&e=1AGXRl

Le document contient en fait deux versions du guide:
- Une version longue au point 3 (page 8)
- Une version courte au point 4 (page 14)

Je crois qu'on devrait se simplifier le travail en se concentrant seulement sur la version courte pour commencer.

**Comment by iolyd** [comment]
Pour référence, il y a aussi un issue en lien avec le cadrage précédent de ce travail: #85

**Comment by frroye** [comment]
@iolyd En attendant de voir/discuter de ce qu'on fait avec les traductions des contenus, j'ai fais une nouvelle branche avec un dossier content qui contient 2 fichiers markdown (fr et en) avec le contenu du guide. Je n'ai pas modifié le contenu du guide par rapport à ce qu'il y a dans le drive, j'imagine qu'on peut discuter demain de ce qui doit être ajusté?

**Comment by iolyd** [comment]
@frroye Good, c'est bon pour la nouvelle branche. Oui, on pourra discuter des ajustements de contenu à faire dans le guide ce pm.

**Comment by frroye** [comment]
Note: À qui s'adresse le guide? Au utilisateur vs au collaborateurs internes? -> au utilisateurs du site en général
