### ISSUE TITLE
Action: Regarder les options pour les traductions de fichiers markdown 

### ISSUE THREAD

**Issue by frroye** [CUPUM/nplex#268]
# Task Description
Regarder les options pour les traductions de fichiers markdown

# List of actions 
- [x] Regarder si Inlang peut être utilisé avec le markdown

**Comment by frroye** [comment]
Voir 
[Document (markdown) support #402](https://github.com/opral/monorepo/discussions/402)
[Fink Vision 24 #677](https://github.com/opral/monorepo/discussions/677#discussioncomment-5842201)

**Comment by frroye** [comment]
Salut @iolyd! J'avais regardé avant de partir pour les traductions des fichiers de contenu en markdown (les deux liens ci-dessus) et je pense si j'ai bien compris Inlang ne les supporte pas. Je ne sais pas vraiment quelles sont les alternatives?

**Comment by iolyd** [comment]
Hmm je vais essayer de prendre un peu de temps aujourd'hui ou demain pour regarder, mais dans le pire des cas il faudra seulement créer le markdown directement dans les fichiers json des traductions (pas la meilleure expérience utilisateur j'en convient). Dans ce cas je vois difficilement pourquoi ça ne fonctionnerait pas comme du markdown c'est ultimement juste du texte (il ne suffira que de _parser_ les traductions au niveau de l'application pour transformer le markdown vers des balises html).

**Comment by iolyd** [comment]
Après une recherche plus poussée et en prévision de certaines fonctionnalités futures, c'est effectivement une bonne idée de rédiger ce type de contenu dans des fichiers markdown indépendants plutôt que dans du markdown géré via la suite de `inlang` / `paraglide`. Les extensions des fichiers markdown seront cependant potentiellement modifiées pour `mdx` ou `svx` afin de s'intégrer avec un pré-processeur markdown pour svelte. (issue à venir pour ce point)
