### ISSUE TITLE
Epic: Développer le contenu du module de carte

### ISSUE THREAD

**Issue by frroye** [CUPUM/nplex#270]
### Epic description

Développer le contenu du module de carte.

### List of tasks

- [x] #161
- [x] #74
- [x] #149

**Comment by iolyd** [comment]
Après révision des issues, je propose de fusionner ce epic avec #80 comme il est en fait ici question de données externes. La gestion du contenu cartographique _interne_, c-à-d issu de notre propre base de données, est déjà couvert par le volet _Développement_ et est au final produit par les utilisateurs.
