### ISSUE TITLE
Meet: In person coordination meeting about Nplex on Apr. 3

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#273]
### Meeting description

Suivi sur l'avancement du projet et l'organisation du travail.

### List of actions

- [x] Action: Schedule meeting with guests
- [ ] Action: Define meeting agenda
- [ ] Action: Share meeting agenda with guests
- [ ] Action: Hold meeting and take notes
- [ ] Action: Convert actionable items to issues
- [ ] Action: Write back to guest(s) with next steps

### Meeting notes

- ...
- ...

### Actionable items

- [ ] Task: ...
- [ ] Task: ...
- [ ] Task: ...

**Comment by sjinko** [comment]
![IMG_0582](https://github.com/CUPUM/nplex/assets/8132989/20974178-444b-43f7-a03a-076d55de3561)
![IMG_0581](https://github.com/CUPUM/nplex/assets/8132989/d89d8394-1868-455a-8f84-aaf1897c4304)
