### ISSUE TITLE
Task: Faire un sprint d'entrée de données avec l'équipe de la chaire

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#287]
#### Drive avec les données

https://drive.google.com/drive/folders/1Q5jrw-kz_cZSnIoWgmsHIRMu1yxICW8x?usp=drive_link

#### Lien vers l'application

www.nplex.design ou www.nplex.vercel.app

### List of actions

- [x] Téléverser les images

**Comment by frroye** [comment]
Maurice martel

**Comment by rsdmu** [comment]
moa

**Comment by roxanekasprzyk** [comment]
Desk

**Comment by sjinko** [comment]
# yh2

**Comment by SarahTannir** [comment]
L. McComber

**Comment by roxanekasprzyk** [comment]
**Rose Architecture**

**Comment by delphineduplain** [comment]
NDA

**Comment by frroye** [comment]
Rayside Labossière

**Comment by hugobb** [comment]
Atelier Marta:
- [ ] Alma
- [ ]

**Comment by sjinko** [comment]
# Paul Bernier Architecte

**Comment by frroye** [comment]
Nathalie Thibodeau

**Comment by SarahTannir** [comment]
nature humaine

**Comment by roxanekasprzyk** [comment]
Natalie Dionne Architecture

**Comment by frroye** [comment]
Atelier Barda

**Comment by delphineduplain** [comment]
Henri Cleigne

**Comment by frroye** [comment]
@delphineduplain ;)
