### ISSUE TITLE
Synthétiser et intégrer les résultats de l'atelier 1 au reste du projet

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#30]
- [x] Réviser les notes de l'atelier 1 et ajuster les issues concernés.
- [x] Rédiger un compte rendu pouvant être partagé avec les collaborateurs
  - [x] Travailler le wiki de nplex pour y intégrer ce contenu: [Voir ici la section _comptes-rendus_](https://github.com/CUPUM/nplex-frontend/wiki/Comptes-rendus)
- [x] Partager le compte rendu avec le comité conseil

**Comment by sjinko** [comment]
J’ai modifié le milestone concerné pour que ce issue soit clos avant l’Atelier 2 (date à définir)

**Comment by sjinko** [comment]
Salut, je valide le contenu du [compte rendu dans le wiki](https://github.com/CUPUM/nplex/wiki/Comptes-rendus) ✌️

**Comment by iolyd** [comment]
Les comptes-rendus ont été partagés et sont progressivement intégrés à la réflexion au niveau du UX/UI.
