### ISSUE TITLE
Task: Mettre en place un protocol de sauvegarde des données importantes 

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex#50]
# Task: Définir un protocol de sauvegarde des données importantes

## Task Description
En référence à l’avertissement de CalculCanada (voir courriel du 12 janvier 2022), il faut mettre en place un protocol de sauvegarde des données importâtes

> From:  <cloud@computecanada.ca>
> Sent: Wednesday, January 12, 2022 12:43 PM
> To: Emmanuel Beaudry Marchand
> Cc: Shin Koseki 
> Subject: Re: [Ticket#0148772] Allocation de ressources par le service d'accès rapide pour un nouveau projet
>  
> Votre projet a été créé sur le nuage Béluga. Connectez-vous par https://beluga.cloud.computecanada.ca/ avec les informations d'identification pour votre compte Calcul Canada.
> 
> * Aucune copie de sauvegarde n’est faite des instances et volumes; n'oubliez pas de sauvegarder ailleurs vos données importantes.
> * Aussi, comme les ressources sont limitées et en grande demande, veuillez supprimer vos instances lorsque vous en avez terminé.
> 
> Consultez la page Lancement de votre première instance par https://docs.computecanada.ca/wiki/Cloud_Quick_Start/fr.

## List of actions
- [ ] Action: définir protocol
- [ ] Action: mettre en place protocol
- [ ] Action: tester protocol

**Comment by iolyd** [comment]
Le nouveau service utilisé au niveau de la base de données (https://neon.tech/) offre une fonctionnalité de backup automatique. À première vue, la gestion _rigoureuse_ et l'éventuelle récupération de ces backups requiert cependant des connaissances CI/CD que l'équipe ne détient pas. Nous devons donc déterminer comment intégrer ces compétences au projet.
