### ISSUE TITLE
Task: Écrire à Geneviève (Inven_T) pour accompagnement au niveau de la recherche de nouveaux financements

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#67]
# Task description

Écrire à Geneviève pour demander un accompagnement au niveau de la recherche de nouveaux financements.

> Bonjour Geneviève,
>
> À la lumière des commentaires assortis à la décision du jury vis-à-vis notre demande déposée au programme Partenariats-UdeM pour le projet nplex, nous aimerions élaborer un modèle d’affaire qui nous permette de continuer le développement de la plateforme et qui garantisse sa pérennité.

> Est ce que vous ou une autre personne du centre Inven_t seriez en mesure de nous rencontrer dans les prochaines semaines afin d'en discuter?

# To do

- [x] Rédiger courriel
- [x] Valider courriel
- [x] Envoyer
- [x] Attendre suivi

**Comment by iolyd** [comment]
Salut @sjinko, avant que je procède à l'envoi, pourrais-tu confirmer que le message préparé pour GL (dans le corps de ce issue) couvre bien ce que nous aimerions voir avec elle / le BRDV au sujet de nplex?

**Comment by sjinko** [comment]
J'ai fait des modifications. Dis-moi si ça te va
