### ISSUE TITLE
Task: Meeting with G. Létourneau-Guillon on Apr. 29

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex#70]
# Task Description

Rencontre d'idéation sur les avenues de pérennisation financière du projet et sur la démarche d'élaboration d'un modèle d'affaire.

# List of actions
- [ ] Action: 
- [ ] Action:

**Comment by sjinko** [comment]
GLT: 
- [ ] Suivi hébergement
- [ ] Suivi Axelys
- [ ] Mise en lien avec le centre d’entreprenariat de l’UdeM

**Comment by sjinko** [comment]
- [ ] @iolyd check out new call Partenariat UdeM to prepare application

**Comment by iolyd** [comment]
Je ferme ce issue. Les tâches sont définies plus en détail dans ce epic: #64, avec des liens vers les sous-issues concernés.
