### ISSUE TITLE
Onboarding: Agathe P. C.

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#75]
# Introduction

Bonjour Agathe, tel que discuté tu trouveras ici quelques informations introductoires de référence pour t'aider à:

- naviguer les outils numériques utilisés à la chaire;
- te familiariser avec le projet _nplex_;
- démarrer ton travail avec quelques tâches.

### Github

Github est la principale plateforme que nous utilisons pour gérer les projets à la chaire. De manière générale, les informations qui te seront pertinentes pour coordonner notre travail se trouveront sous l'onglet [**_Issues_**](https://github.com/CUPUM/nplex/issues).
<img width="276" alt="Screen Shot 2022-05-11 at 11 37 50 AM" src="https://user-images.githubusercontent.com/52970928/167890530-a5ddb7b5-45c6-4135-8f7c-113f140960ec.png">
Pour explorer les _issues_, il est aussi possible d'utiliser [la vue «projet»](https://github.com/orgs/CUPUM/projects/23), qui permet d'organiser et de trier les éléments avec plus de flexibilité. Une documentation plus statique du projet est cependant aussi disponible sous l'onglet [**_Wiki_**](https://github.com/CUPUM/nplex/wiki), où tu pourras entre autres trouver [les comptes-rendus des activités passées](https://github.com/CUPUM/nplex/wiki/Comptes-rendus).
<img width="339" alt="Screen Shot 2022-05-11 at 11 40 40 AM" src="https://user-images.githubusercontent.com/52970928/167891352-6df140bf-4d14-4532-9822-54a7dc4b6374.png">

### CIRRUS

Nous utilisons principalement la plateforme [CIRRUS](https://cirrus.gnp.umontreal.ca/) pour le stockage infonuagique et le partage de fichiers non-code entre membres de la chaire. Je vais entreprendre la démarche pour y initialiser un compte associé à ton adresse institutionnelle. Une fois ce compte inscrit, il sera possible pour toi de t'y connecter en utilisant l'option «Se connecter avec son compte UdeM». La page d'accueil présentera alors les documents et dossiers t'étant partagés ou tout autre contenu créé ou téléversé via ton compte.

### Figma

Tu devrais maintenant avoir reçu une invitation pour rejoindre la plateforme [Figma](https://www.figma.com/) et le groupe de la chaire (CUPUM). Cet outil pourra être utile pour concevoir et partager des documents de nature plus graphique, tels que des présentations, des schémas, etc. Nous l'utilisons aussi parfois comme tableau (_whiteboard_) pour prendre des notes lors de séances d'idéation ou lors de rencontres d'équipe lorsqu'un format plus spatialisé se prête bien à l'exercice, mais de manière générale les notes de rencontre sont directement intégrées en format texte aux issues sur GitHub.

# Tâches 🏁

Pour cette semaine et la semaine prochaine, je te propose de compléter progressivement les tâches restantes ci-dessous. N'hésite pas à commenter ce _issue_-ci si jamais tu as une question ou si tu rencontres un problème.

- [x] @iolyd: Créer un profil et un compte GNP pour l'arrivant
- [x] @iolyd: Ajouter l'arrivant à l'organisation GitHub
- [x] @iolyd: Ajuster les permissions sur GitHub en assignant une équipe
- [x] @iolyd: Inviter l'arrivant au groupe Figma
- [x] @iolyd: Introduire à Github
- [x] @iolyd: Introduire à CIRRUS
- [x] Lire la fiche de présentation sommaire du projet: https://github.com/CUPUM/nplex/wiki/Charte-g%C3%A9n%C3%A9rale
- [x] Lire les comptes-rendus: https://github.com/CUPUM/nplex/wiki/Comptes-rendus
- [x] Développer le issue: #74
- [x] Identifier des angles morts et proposer/souligner de nouveaux enjeux en lien avec la présentation du projet, les comptes-rendus, ou le issue identifié ci-haut

**Comment by AgathePC** [comment]
@iolyd Un message apparaît disant que mon compte est non approvisionné. Peut-être que cela prend un peu de temps avant de se mettre à jour.

**Comment by iolyd** [comment]
@AgathePC Reçois-tu la même erreur aujourd'hui?

**Comment by AgathePC** [comment]
@iolyd Oui. Voici le message : _Compte non approvisionné.
Votre compte n'est pas approvisionné, l'accès à ce service n'est donc pas possible._ Je pourrai partager mon avancement autrement en attendant.

**Comment by iolyd** [comment]
@AgathePC C'est bon. Un partage du fichier via le OneDrive institutionnel devrait bien fonctionner pour l'instant. Entretemps je vais vérifier avec l'équipe technique de CIRRUS s'ils arrivent à identifier la source du problème.

**Comment by AgathePC** [comment]
@iolyd j'ai maintenant accès à CIRRUS
